### ISSUE TITLE
Rename Repository from Transfer to voxpupuli

### ISSUE THREAD

**Issue by TraGicCode** [voxpupuli/puppet-stackify#6]
I just migrated this module over to vox.  Can someone with admin permissions rename it to puppet-stackify instead of tragiccode-stackify?

**Comment by bastelfreak** [comment]
Done. Missing:

* add to plumbing
* add to modulesync_config
* do a modulesync
* do a release

I will take a look at those topics tomorrow

**Comment by TraGicCode** [comment]
voxpupuli/modulesync_config#383

**Comment by TraGicCode** [comment]
voxpupuli/plumbing/pull/141
I think i need you to add it to the modules secret section.  I don't think i can do this part.

**Comment by TraGicCode** [comment]
@bastelfreak Did you not need to update the secret section for voxpupuli/plumbing#141 ?

**Comment by bastelfreak** [comment]
The secrets are normally generated directly at master: https://github.com/voxpupuli/plumbing/commit/a080950ac28d20715e693d2cef60ea2bc4301acf

**Comment by TraGicCode** [comment]
@bastelfreak Can you merge this module sync?  I also added a new task of fixing rubocop issues.
